# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0522b5eb93ad2fc573a9f459f5bad0b660316ef8d829a6b3b697d264de7306e14d3d124f8bae3ec93fe290610e591d6bbaa666e4ff352a2fce9c8323a2a4c2e3

test:
  secret_key_base: 2fdd6d809238fd407585fdfe9339732258ffb8ef1d43e9b121cfa9b77cd68f18ff2f20b3c43ae074e5e96ced51f6b3719db4295791d453679370e4a1e990dbbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
